### PR TITLE
Ice and Fire 1.20.1 port

### PR DESCRIPTION
**Pull request by SidPrinceDesFlammes**

### CODE REVIEW

**Comment by TheBv** [comment]
I've skimmed through it and it looks pretty good! :D
Thanks a lot for your work :)
I won't have time to look at how to resolve the structure related stuff until the weekend so if you want to work on that before that I won't complain. I'll just try catch up with you on the status when I next have the chance to work on this mod.

**Review by GizmoTheMoonPig — CHANGES_REQUESTED** [review]
Few nitpicks about what I've read through so far:
- Materials need to be replaced with a set of block properties to mimic the old behavior, you cant just outright remove them. I made a gist [here](https://gist.github.com/GizmoTheMoonPig/77a90a48e0aeecd15b4c524e1c7f0a4a) that explains what properties to use for each material.
-  Things like Vector3f.ZP and Vector3f.XP can be replaced with Axis.ZP and Axis.XP in the com.mojang.math folder instead of creating new quaternions each time. Not a necessary change but is easier to read. 
- Instead of rounding BlockPos params, use BlockPos.containing. It'll automatically floor the numbers which is what Mojang does. 

I still need to carefully look over the bestiary screen as GUI code changed a LOT between 1.18 and 1.20. Everything else looks pretty good so far.
(I'm aware I don't work on this mod, but I felt like reviewing the port anyway since I have a ton of experience porting mods)

**Comment by TheBv** [comment]
I second what Gizmo said especially the third point.
Personally I don't care too much for the second point but it'd still be nicer (maybe an optional thing to do at the end).

Also if people want to comment on any piece of code it is much appreciated (at least from my view); the more opinions you get the better :)
Oh and thanks!

**Comment by SidPrinceDesFlammes** [comment]
I am working on the Materials, should commit the changes tomorrow

**Comment by SidPrinceDesFlammes** [comment]
[iceandfire.zip](https://github.com/AlexModGuy/Ice_and_Fire/files/12534950/iceandfire.zip)

Here is the folder containing the nbt files of the Mausoleum, Graveyard and Gorgon temple
I'll try to include them

**Comment by SidPrinceDesFlammes** [comment]
The problems I have now come from the fact that : 
CONFIGURED_FEATURES is in Registries and not BuiltInRegistries, so it is a ResourceKey to the Registry and not the Registry itself
JigsawConfiguration has been deleted and I can't find any equivalent or if it is needed

Maybe I still don't see how to register the structures based on the json
Maybe we can pause this, see if it is possible to use my changes to speed up 1.19.X and come back to this later ? Or if anyone can help

**Comment by TheBv** [comment]
I think 1.19 has the same issues as 1.20 as far as structures are concerned. I was just planning on backporting from 1.20 to 1.19.
I'll try take a look at your changes as soon as I can. And hopefully figure out the structure issues.
Honestly for now it might just be fine to comment out all the structure code and then make sure that otherwise things "somewhat work".
If we can run the mod it'd then also be easier to reintroduce the structures to the game :)

**Comment by DonorKrovi** [comment]
Nice job!

**Comment by TheBv** [comment]
Okay I've went and resolved all remaining compiler errors.
For now I've commented out the structure code.
I've also made the switch to NeoForge and updated the gradle version, both in line to current progress in AlexsMobs.

What we now have left is the fun part of finding various problems of which there will be many I'm sure.
I'll look into them in the coming days :)

**Comment by SidPrinceDesFlammes** [comment]
I was literally doing the same work yesterday evening but did not have time to finish the job.
Thanks ! Let's start the happy testing :D

**Comment by DonorKrovi** [comment]
So far, the game ends at the moment of "Creation of the World", so good luck and thanks to you
https://mcpaste.io/b045e779485fe16a

**Comment by TheBv** [comment]
Went ahead and modernized a lot of the mod and laid down the basic framework for datagen stuff.
Ideally in the future we'd convert a lot more things to make use of that but for now it's fine.
There's still some issues with the features. For some reason pixie villages are generated A LOT. I'll look into that some other time.
I've noticed a lot of lag spikes and other issues which I will try to fix next, short list of things:

- Mausoleum spawners not being happy
- Game crashing on world gen
- Poor TPS performance

**Comment by TheBv** [comment]
I'm quite happy with the progress.
The only thing that's missing right now are villages. I'll merge this PR for now. If there's anything else you want to work on you can just create a new one and I'll take a look at it.
Thanks for all your work!

**Pull request merged**
