### PR TITLE
(1.16) Optimize and clean-up GUIs

### PR DESCRIPTION
**Pull request by Matyrobbrt**
This PR optimizes and improves GUIs:
- useless casts are removed
- `@OnlyIn` is removed (see #4454 as to why)
- deprecated methods are replaced with their equivalents
- the container registry uses `DeferredRegister`, which is a future-proof method of registries, as in 1.18.2 the static init (the method that is currently used by the _entire_ IaF codebase) way of registering won't work
- useless casts and checks are removed
- useless assignments are removed
- unused local variables and fields are removed

### CODE REVIEW

**Comment by Matyrobbrt** [comment]
Conflicts fixed.

**Comment by TheBv** [comment]
This seems to have broken the ice and fire main menu screen. Or at least the rendering for the buttons. 
image

**Comment by Matyrobbrt** [comment]
Hmm. Weird. Let me take a look.

**Comment by Matyrobbrt** [comment]
Ah, I know what broke it. I'll PR it in a second.

**Comment by Matyrobbrt** [comment]
@TheBv #4466 Should fix it

**Pull request merged**
