### PR TITLE
Fix stage 1 dragons teleports when put down. #4718

### PR DESCRIPTION
**Pull request by quinnfrost**
By making dragons on shoulder movement blocked will disable their AI and navigator and fix the teleport issue.

### CODE REVIEW

**Comment by TheBv** [comment]
I went ahead and fixed this in a different way.
Also I feel like your changes aren't the same anymore since the one you sent were quite a bit different (in the commit discussion) ?

**Comment by quinnfrost** [comment]
My bad. This is another way to fix which I believe is a little better than the quick fix in the commit discussion, to use the vanilla `isMovementBlocked` critria. It prevents the ai system and navigator from updating (the same way how the sitting dragons bypasses this issue) so the navigator can never mess up with the dragons sitting on shoulder, even if some where else has. 
Anyway, glad to see it fixed ;)

**Comment by TheBv** [comment]
I saw that but I was a bit hesitant to use that function since it's usage was somewhat inconsistent, and I was worried about potential side effects. At the same time this would eliminate other issues in case someone changes the code in the future.
Although I am seeing it's being used for when a player rides a horse, but not e.g. when a dog is told to sit/ a cat sleeps. 
Inconsistencies I guess...
Either way I guess it won't hurt to implement it :)

**Comment by quinnfrost** [comment]
Exactly, I believe the vanilla wolves and cats and our dragon entity use a high priority goal `SitGoal` to block movement when sitted. The difference is that wolves and cats don't 'ride' other entity, which dragon does. The only similar vanilla entity is the parrot, however parrot entity is removed after they have mounted the player, and respawned after dismount. I believe that is unacceptable for our dragon entity since no entity present means no ticks and updates. So not that inconsistence I guess.
Btw if you try to assign a destination to a vanilla wolf that is sitting (using vanilla navigator `tryMoveToXYZ` method), you can see the sitting wolf crawls to the destination - in a quite funny way. Their movement can be messed up if something steps in.
If we're using the AI goal system then I guess we'll need another high priority goal to block other goals from running. But since we have the new brain and task AI system in the newer version of the game (which something I'm trying to do - porting the dragon AI to the new brain system, for fun ;) ) I do think the AI system is not the best place for the logic that determines if dragon can move or not.
Side effect is a real issue though, but I don't see any `isMovementBlocked` used in codes other than `LivingEntity#livingTick`, so it should be fine, for now...

**Comment by TheBv** [comment]
That would be very much appreciated. I know Alex has plans to move the dragon ai to the new brain system as well :)

**Pull request merged**
