### PR TITLE
More fixes

### LINKED ISSUE #3319: fairies keep following you

### LINKED ISSUE #3324: Bestiary/Lectern Doesn't Consume Manuscripts
If you use the lectern to fill entries in the bestiary you can take the remaining manuscripts out, put them back in or exit and re-enter the lectern which returns the initial manuscripts. The lectern still fills out the book, so at least that's working properly.

Version: 2.1.4 - 1.16.4
Forge: 35.1.4

### LINKED ISSUE #3397: Server Dragons on shoulder
If i pick my dragon on to my shoulder it also is visually on my friends shoulder

### LINKED ISSUE #3401: [Compatibility] Common Forge OreDict tags missing from ores
All of your metals and gemstones are properly tagged, but the ores are not, which makes them unprocessable by other mods that would otherwise be able to (create, immersive engineering, etc).

### LINKED ISSUE #3406: Gorgon Head turns Mobs to Stone through Walls and Isn't used Up after Using it
Used Gorgon Head in a Creative World(The World Is Started In Creative but I was in Survival Mode when I used The Gorgon Head). And I used the Head I thought wat because I heard The ,,you turned something to stone`` sound  I was in My house and there were no Mobs there. I then walked Out and saw that I turned One Of My Golems that are Guarding my house to stone(The Golems are from the Extra Golems Mod) I then used the scout Enchantment from the better default biomes mod(the Enchantment makes mobs In a certain Area Around the Player have the glowing effect) to locate a Mob in This case a Orca from Alex Mobs Mod I placed myself behind a Block and Used The gorgon head and turned the Orca from behind a Wall to Stone. Also the Gorgon head wasn't used up from my inventory. I was in Survival Mode!!!

### LINKED ISSUE #3409: Ice and Fire 2.15-1.16.4 Hippocampus
Newest version of the mod broke being able to ride a tamed hippocampus. As soon as I mount a hippocampus it immediately throws me off, not letting me be able to ride. It happens on single player and on server. It lets me ride on land but as soon as I go under water it throws me off.

### LINKED ISSUE #3411: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
Can someone help me ?,
I can spawn the dread knight horse in client without any problem.
But when I spawn the horse in my modded survival server, it crashed.

[08:19:02] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 767c6076-ce3f-4e10-9b39-2d336a65c71b
[08:19:02] [Server thread/ERROR] [minecraft/ChunkSerializer]: An Entity type entity.iceandfire.dread_horse has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.crash.ReportedException: Saving entity NBT
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1433) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:betterendforge.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_184198_c(Entity.java:1347) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:betterendforge.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_70039_c(Entity.java:1355) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:betterendforge.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:303) ~[?:?] {re:classloading}
        at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:682) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ChunkManager.lambda$save$9(ChunkManager.java:351) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_275] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_275] {}
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_275] {}
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_275] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_275] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_275] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_275] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_275] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_275] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_275] {}
        at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:348) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerChunkProvider.func_217210_a(ServerChunkProvider.java:307) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:698) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:531) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
Caused by: java.lang.NullPointerException
        at com.github.alexthe666.iceandfire.entity.EntityDreadHorse.getCommanderId(EntityDreadHorse.java:96) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
        at com.github.alexthe666.iceandfire.entity.EntityDreadHorse.func_213281_b(EntityDreadHorse.java:57) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1412) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:betterendforge.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        ... 23 more

### LINKED ISSUE #3416: Sticky Chain Lines and Standard Chain Lines roles are reversed
When trying to use two chain lines, chains will only attach mobs to other mobs and will be unable to be taken off the mob. IE, are acting as what the sticky chains should be doing. When using Sticky Chain Lines, they will work as standard chains should be doing and not stick to other mobs. I have been able to recreate this multiple times across multiple worlds (in fact, I haven't been able to do otherwise)

### LINKED ISSUE #3424: Version 1.16.4 Modversion 2.1.5 Dreadstone including Dread Wood can be broken just like Normal
Found the Dread Structure and gone Up to it The One Prop Mod (Hawaila for 1.16.4) told Me that I needed a Pickaxe thats breaks Obsidian (Diamond Pickaxe or higher) I had a Dragonsteel Pickaxe so I mined with my Pickaxe, I was able to break the Dread Stone. Then I walked to the Front Gate and I was Able to break the Wooden Door with any Axe.
I think this is a Bug because ,Don't you have to get a Key to get Inside. By the way The Dread Blocks are Blast Resitant I wasn't able to Blow them Up with exlosions but I am able to mine the without a Problem

### LINKED ISSUE #3433: Sheep huddling together and spawning alot
On my server I installed ice and fire and I noticed alot of sheep are spawning but they also are huddled up in groups of 3 sheep. 
I tried without ice and fire and this issue wasnt there.
After I installed the mod again there where huddles of sheep.

What is causing this and can I turn it off cause it looks like a sheep invasion

### LINKED ISSUE #3442: "Death Worm Spawn Weight" acts as "chance" iceandfire-2.1.5-1.16.4
"Death Worm Spawn Weight" = 1000 spawns less worms even though the comment says lower = less worms.

I'm going to continue testing, I think most of the weights are weights and so on but I noticed an ass-ton of worms when set to 1. XD

Included list of mods in case.

[list.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5820361/list.txt)

### LINKED ISSUE #3449: Ice and Fire dragon pathfinding crash
Ice and fire dragon crashing due to IStuckHandlerEntity. Rats mod had a similar issue (as I was the one who made the git) but has been fixed, maybe the same concept can be applied here?

[crash-2021-01-16_16.35.46-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/5824751/crash-2021-01-16_16.35.46-server.txt)
https://pastebin.com/gYp7ZSvV

Git Link from rats mod: https://github.com/Alex-the-666/Rats/issues/513

### PR DESCRIPTION
**Pull request by TheBv**
Well here we go again. This will continue being a draft until I feel like I've addressed enough issues or one of very high importance. Or alex want's to merge them.
This used to include changes from wchen1990 but I removed them to keep the requests separate 
Fixed:

- Fixed Gorgonhead not breaking after one use and being able to hit enemies behind walls (resolves #3406)
- Fixed dread knight horse spawning issues (resolves #3411)
- Lightning Dragons are now immune to lightning bolts, get healed when struck and are shortly immune to fire (to avoid burning damage)
- Sticky chains and normal chains aren't swapped anymore (resolves #3416)
- Fixed Hippocampi' not being able to be ridden underwater in newer forge versions (resolves #3409)
- Made sure that dragons can also be ridden in water because they could previously
- Should have fixed most desync issues related to "riding" dragons (should resolve #3397,#3374 and more)
- Fixed myrmex being always "right-clickable"
- Pixies now can't steal for you for 10 seconds after having failed to do so (resolves #3319)
- Dreadstone can't be broken anymore (resolves #3424)
I can't implement the previous implementation of dreadstone being breakable if it was placed by a player. The only way to achieve this in the new versions of minecraft would be to create a second dreadstone block that would be breakable.
- Reduced hippocampus' swim speed by a bit to make it more manageable #3259
- Tamed dragons shouldn't attack tamed entities anymore in most scenarios. (Maybe this should be an option in the configs)
- Fixed some phrasing issues in the config. (resolves #3442)
- Fixed the pathfinding stuck handler issue the same way it was fixed in the rats mod (resolves #3449)
- Fixed wandering cyclops not spawning. Indirectly also resolves #3433
- Manuscripts are now also being consumed on servers (resolves #3324)
- Forge ore tags are now properly working (resolves   #3401)

### CODE REVIEW

**Comment by Carro1001** [comment]
Could you perhaps look into lightning dragons being damaged by the lightning that is summoned once they hatch? this didn't happen before and hopefully ya can fix it

**Comment by TheBv** [comment]
I'd like to address that dreadstone is breakable next (#3424) but I'm uncertain as to what behavior alex want's.
I'm assuming you should be able to break it after you've used the key but maybe you shouldn't be?
If anyone knows which behavior alex wants that would be great. 
In general I have some more questions about the way things should be implemented. For instance if the gorgon head should only select entities that where "raytraced" or if tamed dragons should attack tamed entities after you've hit them(#3385) and some other things.
So if anyone roughly knows how any of these things "should" be please let me know!
Here's my discord as well Bv#0365

**Comment by BugmanBugman** [comment]
I believe dreadstone is supposed to be unbreakable the entire time, it was like this in previous versions so I think that’s how alex wants them.

For the tamed dragons, i think most players would agree that they were prefer if they didn’t attack eachother lol. Dragons can cause a lot of damage and it would be annoying to have your base destroyed just for having your pets together

**Comment by BugmanBugman** [comment]
For “ Fixed some phrasing issues in the config. Also currently non of the custom mobs can spawn "naturally" like sheep is that intentional?”
Im wondering which mobs do you mean. I know cyclops are supposed to spawn as wandering cyclops with sheep naturally instead of structures

**Comment by TheBv** [comment]
From looking at the code there are some things that would indicate that at some point mobs like sand worms and others might have been able to spawn normally like zombies or skeletons have or at least that's how I interpret some of the code.
I could of course be entirely wrong and the more I think about it the more I think some of the functions are just left there in case you might want to check for certain things.
Main reason why I brought this up is because the config option `Death Worm Spawn Check Chance` is in it's current implementation entirely useless. Also all mobs that spawn in the world e.g. Sea Serpents, Hippocampi' etc. use config value `Chance` but for some reason for the death worm it's swapped. It's using the config value for the `rate` instead of the `chance` but the values seem to be correct. Also some mobs like cockatrice have their chance to spawn set to 0 by default no idea what that's all about. 
I dunno there's a bunch of weird inconsistencies that I don't quite understand yet and the more I look into it the more confused I become. 
Thanks for bringing up the cyclops stuff! I've found the reason why they aren't spawning and I understand the "mob spawning code" a lot better I'll fix it in a bit! (also related #3433)

**Comment by tweakbsd** [comment]
Great idea healing a lightning dragon from a lightning bolt in my opinion. The code that does this should btw not use string comparison a little bit cleaner would be:

`
    @Override
    public boolean isInvulnerableTo(DamageSource i) {
        if(i.damageType.equals(DamageSource.LIGHTNING_BOLT.damageType)) {
            this.heal(15F);
            return true;
        }
        return super.isInvulnerableTo(i);
    }
`

**Comment by tweakbsd** [comment]
I'm agreeing on most ppl saying your own dragon should not attack each other, therefore I implemented that in my 
fork so dragons with same owner don't attack each other. Which essentially comes down to this in  **EntityDragonBase.java**

`
    @Override
    public boolean shouldAttackEntity(LivingEntity target, LivingEntity owner) {
        if (this.isTamed() && target instanceof TameableEntity) {
            TameableEntity tamableTarget = (TameableEntity) target;
            UUID targetOwner = tamableTarget.getOwnerId();
            if (targetOwner != null && targetOwner.equals(this.getOwnerId())) {
                return false;
            }
        }
        return super.shouldAttackEntity(target, owner);
    }

`

I also thought of the idea that using same team as an indicator wether to allow attacking could be the way to implement it. But it's a question of design that Alex should decide if he at all want's tamed dragon's not attacking each other.

**Comment by TheBv** [comment]
@tweakbsd I implemented shouldAttackEntity in my draft if you want to make your own pull request I can remove the code? I think yours is a lot nicer and mine did have some issues associated with it.
And thanks for mentioning the stuff with the invulnerability I'll change it shortly!

**Comment by tweakbsd** [comment]
@TheBv You're welcome of course. If you want you can use any of my code in your draft. I appreciate every bit and everyone contributing to this mod.  I'm not going to do a PR for that few lines of code for now. My next PR will take me quite some time still.

**Pull request merged**
