### PR TITLE
Various bug fixes and optimizations

### PR DESCRIPTION
**Pull request by wchen1990**
- Upgraded the minimum forge version to 34.1.21 to use Biome Dictionary for biome configuration
- Also allows for more versatile Biome configuration now
- Fixes issues with spawning certain creatures that were added as Features during Chunk generation
- Many files have their imports cleaned up

### CODE REVIEW

**Comment by wchen1990** [comment]
Seems like Eclipse was very zealous with cleaning up those imports...

**Comment by wchen1990** [comment]
Should resolve a lot of the X thing doesn't spawn issues (#2977, #2991, #3007, etc)

**Comment by Carro1001** [comment]
You the MVP

**Comment by BugmanBugman** [comment]
Was #2976 fix implemented? Either way, this is amazing and thank you so much

**Comment by wchen1990** [comment]
Added the proposed fix for #2976 to this PR.

**Comment by Vexhaust** [comment]
damn man,i dont know how to fix it through this

**Comment by wchen1990** [comment]
The changes to IafDragonDestructionManager should resolve the issues with dragons freezing the server when dragon griefing is turned on.

**Comment by BugmanBugman** [comment]
Doing god's work here, thank you so much

**Comment by wchen1990** [comment]
@Thombias If you tried making a resource pack and it didn't work that's strange. It should've worked. I'm assuming your resource pack looked something like:
```
yourdatapack
- pack.mcmeta
- assets
-- iceandfire
--- sounds.json (the edited one)
```

Alternatively, you can try overwriting the sounds.json file in the jar.

**Comment by Thombias** [comment]
Ok now i've got some time to give this another try aaannnd... well, i unfortunately still can't get it to work:
- Editing the sounds.json from the mod jar file and replacing all the code with this -> I get no sounds at all from Fire & Ice
- Creating a seperate respource pack with this sounds.json -> All sounds at original volume
- Same as option 2, but i included the sounds folder + all sound files -> Still everything at original sound volume

I've done the resource pack correctly, all necessary folders and files where they belong. I'm kinda lost right now. :(
I still haven't figured out how to make a data pack, unfortunately there's nothing on the internet that shows a data pack with a sounds.json file and where it belongs, etc. (Or rather, i haven't found anything about this yet)

**Comment by wchen1990** [comment]
@Thombias That's weird.

I guess you'll have to wait for Alex to officially release a jar with this branch merged in. Or you can always try building the jar from source if you're really impatient.

**Comment by Carro1001** [comment]
Would you be able to fix the issue with an unidentified method for the ghost chest? These two functions don't appear to exist anymore and seem to be the cause for it to not work in newer forge versions for 1.16.3
image

**Comment by AlexModGuy** [comment]
@Thombias @wchen1990 I'll be building the new jar with some minor other commits first. expect a 2.1.1 this week.

As for the contributors to fix these issues, I can't thank you enough :)

**Pull request merged**
