### PR TITLE
Dragon ride redone

### PR DESCRIPTION
**Pull request by quinnfrost**
This is not a bug fix, this is a dragon riding system redone. Mainly it smooth the ride by letting clients to do the motion stuff, just like how vanilla horses are doing. I tried to left everything else untouched but I haven't test it extensivly. So it might be buggy.
But if you're interested, here's what I've done so far:

- A completely redone over the dragon riding system ( for players to ride so far ), by the idea of how vanilla horses are done.
- Flying near the unloaded chunks are no longer laggy, no more weird friction in the air.
- Riding movement is now handled by the client, the server knows nothing about `deltaMovement` now.
- The old "AI+move controller" riding system is disabled for the dragons, but not deleted.
- Anything that tries to access `setDeltaMovement` on server side during the ride is disabled, such as the flight manager, since that will cause dragons to halt.
- Riding related stuff from `IafDragonLogic` is moved to `EntityDragonBase`
- Dragons can now move sideway and backward correctly. Sprint key has its uses now as well.
- Dragons now need time to accelerate, they don't reach their max speed instantly. This changes the feeling how the dragon is handled.
- Ice dragons goes faster in water, fire dragons goes faster in lava. Nothing for lightning dragons so far.
- Riders no longer dismount at dragon's feet, they will now positioned right where they are after dismount.
~~~
The following might affect AI controlled movement as well
~~~
- Elder dragons no longer slow down and swim in shallow water. This modified the `isInWater` method and will influence everything like the AI system and animation system. For bigger dragons doing this will prevent them from swimming in the air.
- Elder dragons have bigger step height, this means they can walk up higher blocks without jumping. The most direct effect is that dragons elder than 55 can walk over fences, though their pathfinder won't deliberately to do that.

Something else:

- Fire dragons no longer sink in lava
- Diving in air with attack button pressed will play tackling animation
- Ice dragons are now unaffected by bubble columns
- Fire dragons are now unaffected by the soul sand

Some idea not implemented:
- Free camera when riding. Not sure how to get hitboxes to their right position.

~~~
Some bug not yet fix
~~~
~~Rare move wrongly problem still exist. Mostly happens when going up hills diagonally~~
Move wrongly problem is fixed by disable the move wrongly check for dragons

I'm not sure if I'm doing this correct but I do believe a smooth ride is critical for our revolutionary dragon experience :), please let me know if I've done something wrong.

Anyway, happy flying.  飞的开心

FYI: Is fandom page still active? I noticed some info is different with what's in the code

### CODE REVIEW

**Comment by TheBv** [comment]
The fandom page is pretty much just maintained by people in the community. So it depends on them updating it.
I'll look at this and the other PR later this week! Thanks for your contribution. 
These are important steps to help transition this mod to the modern minecraft era!

**Comment by TheBv** [comment]
I see you keep adding things just let me know when you think you're completely done with what you want to do and I'll take a look again :)
Thanks!

**Comment by quinnfrost** [comment]
Well that's all I have in mind for now, hope you enjoy it. Sorry for the late reply, been busy recently.
The basic should work fine now, but I haven't test it in a complete playthrough or along with other mods for now, so it might be buggy elsewhere.
Don't forget to mention this (and me ;)) in the change log when you decide to let everyone else to try

**Comment by TheBv** [comment]
Just tried it out and it seems to work pretty well!
There does seem to be an issue with dragons getting stuck mid air though.
Happens when the player uses the dragon flute while the dragon is flying(in escort mode). 
They just walk around very slowly mid air. Also while dismounting dragons for the first time they seem to be heading to the 0,0 coordinates.

**Comment by quinnfrost** [comment]
Glad you enjoy it. I replicated the issue just now, I might have broken some of the AI system, can't believe I've missed that. I'll try get it fixed this days, shouldn't be too hard to fix.

**Comment by quinnfrost** [comment]
These two issues should be gone now, the tickStill and noGravity tag is correct now.
There is one final move wrongly issue when dragon's boundingbox tries to clip a block with very small overlaps, in such case the server side movement check is unhappy with the client collision result and causes movement to stuck, especially for big dragons. I'm not very sure what caused it.
If this happens too often and too annoying, set the noPhysics tag in `move` should get rid of that. However that does disable the server side movement check (especially the block collision part). But since the original riding system does not have movement checks as well, so I guess this might be the proper solution for move wrongly issue.
I'll look into that for a while and if I can't get it done proper I'll just set the noPhysics tag to temporary get rid of the annoying move wrongly stuck and console message, so there might be a small, final commit recently.
Anyway, if you ran into any trouble with the new flight system, let me know and I'll try fix them

**Comment by quinnfrost** [comment]
It's all set, I don't have anything else to patch now.
I don't have time to test it extensively recently, so if you find a bug please let me know

**Pull request merged**
