### PR TITLE
Attempt to fix MultiPart issues

### LINKED ISSUE #5089: [Bug]: Dragon spamming the log
### What happened?

I dont know if its due to Ice and Fire or not, but here's my problem :
Ice and Fire is spamming the console on my server with :

[16Jan2024 23:27:29.529] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]

If I tp to 207 2 3331 I found this electric dragon : 

The dragon fly, sleep and attack normally but he is spamming the log.

I was using versions on github before this one but I didnt do a lot of testing because they were rare to found.
But the electric dragon at the surface was not spamming the log.

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1-beta-2

### Citadel version

citadel-2.4.9-1.20.1

### Relevant log output

```shell
Too long to be put here.
https://mclo.gs/u6ysyfe : start at line 2826
Here's a little part :
[16Jan2024 23:27:29.529] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:29.584] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:29.638] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:29.677] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:29.725] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:29.781] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:29.826] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:29.883] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:29.930] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:29.984] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.028] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.075] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.141] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.176] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.226] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.277] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.366] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.399] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.442] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.485] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.530] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.578] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.630] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
[16Jan2024 23:27:30.676] [Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: EntityDragonPart['Dragon Part'/2056, l='ServerLevel[world]', x=207.17, y=2.42, z=3331.52]
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

### PR DESCRIPTION
**Pull request by SiverDX**
might fix #5089

### CODE REVIEW

**Comment by SiverDX** [comment]
if this doesn't work we might have to go back to the first approach (first commit with the for loop)

(because there then seems to be a disconnect between the known uuids and the one returned by the section of the getentitites call, not sure if that is technically possible - haven't looked that deep into it)

**Comment by TheBv** [comment]
I mean ideally we replace the entire multipart system with the default forge/vanilla one.
I tried doing that a year ago or so I might look into it again.
But besides that this might be a good temporary fix.

**Comment by DigitalWendigo** [comment]
Sorry to intrude, but I agree replacing it might be the better option in the long run. 
Looking at the Deuf mod issue tracker, some people have mentioned that the way Deuf handles the duplicate issue, is by going through every possible number combination it can to try and assign it a different number. 
However, this doesn't always work, and even the creator of it mentioned that "From what I understand, it works for some people and for some it does not." - Link to the mentioned issue is found here: https://github.com/CAS-ual-TY/DuplicateEntityUUIDFix/issues/2

**Comment by SiverDX** [comment]
that issue is kinda useless considering its age
the way deuf handles things is a lot different and less likely to break

in the past it seemed to listen to chunk loading events and work off of that
now it checks when an entity joins a level and uses the vanilla provided method of getting an entity by uuid

**Pull request merged**
