### PR TITLE
Fixes a few typos and amends de_de.json

### PR DESCRIPTION
**Pull request by dequbed**
Just a few I saw during playtesting, not an exhaustive check

### CODE REVIEW

**Comment by tweakbsd** [comment]
Thanks for the fixes! I did the initial translation, so my fault ;-)

**Comment by TheBv** [comment]
I think "Brauner Pilz Feenhütte" should be consistent with "Rote Pilz Feenhütte".
I can see why you changed it in the first place but I'd also suggest possibly renaming it to: "Feenhütte aus rotem/braunem Pilz"
Since "Brauner Pilz Feenhütte" sounds kinda strange to me. (it feels a bit weird to write this all in english ^^")

**Comment by dequbed** [comment]
> I think "Brauner Pilz Feenhütte" should be consistent with "Rote Pilz Feenhütte".
> I can see why you changed it in the first place but I'd also suggest possibly renaming it to: "Feenhütte aus rotem/braunem Pilz"

I'm not to happy with the names for all the pixie homes, I feel a compound noun like "Eichenstammfeenhütte" resp. "Braune/Rote Pilzfeenhütte" would be a better fitting name, or like you said going with "aus \<material\>".
In general I can see a few places where compound names would be better suited, and a lot of inconsistencies in that regard (e.g. sometimes it's "Wüstenmyrmex", sometimes it's "Wüsten-Myrmex").

**Comment by dequbed** [comment]
I updated the translations some more, I would be glad about comments. Especially for the modifiers I'm unsure how to translate a few of the references.

**Pull request merged**
