### PR TITLE
remove citadel biome config usage for structures (1.19.2)

### LINKED ISSUE #5146: [Bug]: Structures spawning on top of oceans
### What happened?

The skeleton of dragons is spawning on top of the water, I assume it should be at the bottom of the ocean, or not be spawning in those areas at all. 
image

image

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1-beta-2

### Citadel version

citadel-2.4.9-1.20.1

### Relevant log output

_No response_

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

### PR DESCRIPTION
**Pull request by SiverDX**
- use vanilla behaviour instead
- no more spawns in water

fixes #5146
(except when spawning on water within said biome - would need some extra checks (e.g. corners of the bounding box) for structures and features to handle that)

### CODE REVIEW

**Comment by SiverDX** [comment]
a potential alternative to doing the additional check for `#forge:is_water` could be to override `biomes()` in `IafStructure` and filter out biomes there

**Comment by SiverDX** [comment]
in general i'd reconsider the usage of biomeconfig
- it generates stale (config) entries
- people don't understand it (especially the negate)
- usually it's not touched (most configs aren't)
- tags work well enough when making a modpack (esp. when using things like kubejs to remove tags - otherwise it'd be a bit more manual work)
  - (the fact that configs are usually not touched still applies, like barely and modpack actually configures stuff) (this includes the bigger ones)

**Comment by SiverDX** [comment]
middle ground would be to add a blacklist tag so that there is a biome tag + blacklist biome tag for each feature & structure
blacklist gets checked first so it can even filter things out which are in the biome tag

makes it pretty easy to understand and there aren't multiple groups etc.

**Comment by TheBv** [comment]
I think I've mentioned this before at some point but the main reason we use the biome config files is just politics.
It's part of the Citadel-system so it will stay as long as the feature persists within it.
Personally I can see why one wouldn't want to use it and move to the vanilla system. 
But since that requires work and offers "less configurability" I don't intend on doing that. 

I think it makes sense to only use tags for structures though, since having two different configs is just silly.

Do you happen to know if we still need to include the custom byg/terallith biomes or have they fixed their tag weirdness?
If you don't know of the top of your head don't worry I'll just look it up myself later.

**Comment by SiverDX** [comment]
The last time I checked Terralith it did use a lot of tags but some biomes were not part of the tags i'd expect them to be (atleast simply going by the name) - don't wholly remember which ones though

BYG uses minecraft and forge tags can't say much past that

forge: https://github.com/Potion-Studios/BYG/tree/1.20.X/Forge/src/main/resources/data/forge/tags/worldgen/biome

**Pull request closed without merging**
