### PR TITLE
bump dragonsteel tier (1.19.2)

### PR DESCRIPTION
**Pull request by SiverDX**
some blocks are marked as needing netherite tools 
dragonsteel should be considered above or equal to it but in its current state it wouldn't considered effective against such blocks

### CODE REVIEW

**Comment by TheBv** [comment]
I think I like the idea behind this idea but I feel like maybe we shouldn't let people just skip the entire netherite system.
I've been considering adding netherite ingot(s) to the recipe somehow.
What do you think?

**Comment by SiverDX** [comment]
could just switch iron for netherite here 
https://github.com/AlexModGuy/Ice_and_Fire/tree/1.19.2/src/main/resources/data/iceandfire/recipes/dragonforge

would slow down the progression a bit more between dragonbone and dragonsteel which seems like a good idea
(would need to recheck if dragonbone harvest tier does not exceed netherite)

alternative could be to add it to the forge core
though the ingot seems to make a bit more sense, especially considering how powerful it is

**Comment by DoctorN0va** [comment]
In relation to dragon steel I would also look at dragonbone/scale weapons and tools and how to make the requirements for their upgrades more steep. 

As it stands dragons are very easy to cheese/kill + dragon skeletons exist, so getting the weapons and tools is VERY simple overall, the scales are def harder as they require the same type, but they are still overall simple to get.

**Comment by DoctorN0va** [comment]
Perhaps changing up the Dragonbone recipe and requiring the combination of a Witherbone and Netherite ingot to create a handle, with the actual blade/use portion of the tools being made from Dragonbone. 

   This could compound down to dragonbone tools actually being what you need in order to gain Dragonsteel ones, being a linear upgrade via the smithing table like you would when upgrading from diamond to netherite. Your keeping the core of the blade as bone, but the outer shell of it is made of dragonsteel type deal 
   
   Could do something similar with dragon scale armor, however that one is a bit harder to argue as making sense, so perhaps it remains as a standalone armor set.

**Comment by SiverDX** [comment]
feel like netherite for dragon bone is a bit much
seems more fitting to only use it for dragonsteel as natural upgrade to it

and dragonbone being somewhere around diamond or higher
also allows you to obtain it from overworld only vs. having to go to another dimension for the ugpraded variant

**Comment by DoctorN0va** [comment]
> feel like netherite for dragon bone is a bit much seems more fitting to only use it for dragonsteel as natural upgrade to it
> 
> and dragonbone being somewhere around diamond or higher also allows you to obtain it from overworld only vs. having to go to another dimension for the ugpraded variant

Valid, I just figured I'd point out the other very clear side of lacking substancial progression with the bone variants, although this also partially a flaw in the way minecraft handles progression itself as well.

**Comment by SiverDX** [comment]
changed dragonbone to harvest level 3 (diamond)
and dragonsteel to 4 instead of 5 (not sure how much the level matters for custom tiers which use the tier sorting registry)

**Comment by TheBv** [comment]
Thanks for your input :)
I'll see what I'll do with it. I think for the beta things can stay as they are and then maybe for a proper new version release I might change things.
I'm currently quite busy with stuff so I don't have the time to look at /merge all your PRs.
But I appreciate them and I'll hopefully get to look at them properly either this or next weekend :)

**Comment by ffuentesm** [comment]
I had a read on this thread and I think the "netherite route" seems more viable. 

1. You swap iron for Netherite in the Dragon Forge recipe
image
2. You make the dragon steel items in the same format as Netherite tools. Add a "Dragonsteel template" item to the dragon roots/caves loot chest. Use dragon bone/scale tools as the base item for the dragon steel upgrade. 
image
image

This way, you lock the Dragon steel gear behind netherite, making the Dragon Bones tools relevant for longer, and if you make the "dragon steel template" a 5% loot on chests, similar to how netherite template is, it will motivate more Dragon hunting. Especially if you make Underground Dragon Nest a Higher % drop for the item.  

Also, I've been thinking, and why the 3 different dragon forges? Why not unify the structure and have the Dragon Blood inside and the dragon you use determines the type of Dragon steel you get out of it? 

Also, would be nice if we could use the Dragon forge as a Blast Furnace or a way to make "cheap Netherite"
image

**Comment by BugmanBugman** [comment]
I think ffuent has the right idea

**Comment by BugmanBugman** [comment]
I think ffuent has the right idea

**Comment by ffuentesm** [comment]
For anyone who wants to test the alternative gear upgrade idea I made, there is a datapack with a tool progression option here. 
https://modrinth.com/datapack/iceandfire_smithing
It's for 1.21.1, but you can easily edit the datapack to work with 1.20 and prior versions. You just need to add the "s" at the end of the folder names.

**Comment by SrNadien** [comment]
> Para quienes quieran probar la idea de mejora de equipo alternativa que desarrollé, hay un paquete de datos con una opción de progresión de herramientas aquí: https://modrinth.com/datapack/iceandfire_smithing . Es para la versión 1.21.1, pero pueden editarlo fácilmente para que funcione con la 1.20 y versiones anteriores. Solo tienen que añadir la "s" al final de los nombres de las carpetas.

Port a mod forma me

**Pull request merged**
