### PR TITLE
fix dragon neck in inventory

### PR DESCRIPTION
**Pull request by quinnfrost**
How to reproduce this issue:
1. Tame a dragon and ride
2. Rotate clockwise/counterclockwise
3. Open the dragon gui to see the neck issue

This issue happens when `yBodyRot` % 360 takes value in (-180, 0) and (180, 360)
Or in F3 screen, keep the yRot value in Facing line negative (`Facing: ... (Towards..) (yRot/xRot)`)

I don't see this happen in 1.20 (yet) since rendering is changed.

Note: This won't fix the neck issue in other mods because it's likely to be a vanilla issue, this only fix the rendering in dragon inventory. The custom `renderEntityInInventory` method is needed to fix this issue.

### CODE REVIEW

**Comment by SiverDX** [comment]
imo would be better as simple mixin which adds these two/three lines instead of copying the entire method

**Comment by quinnfrost** [comment]
I'm trying to avoid mixins here since other mods might use this method, and I'm not sure what side effect of adding this lines
I'll work out a mixin fix in another pr, maybe

**Comment by SiverDX** [comment]
you just check if the entity is a dragon from this mod...?

**Comment by GizmoTheMoonPig** [comment]
Please dont use a mixin for a small trivial fix like this. Theres absolutely nothing wrong with copying the vanilla method and changing things as needed. You should only be using mixins when you absolutely have to, this isnt one of those cases.

**Comment by SiverDX** [comment]
not too sure about that tbh, that leads to countless (large) copies of vanilla code which never gets maintained, is often unreadable, unexplained and runs out of sync with vanilla

**Comment by GizmoTheMoonPig** [comment]
then maybe document where its from? If you copy a method, its good practice to cite where you got it from anyway. If it breaks in some way you can go back and check the OG method to see whats different. Its not hard to maintain something like that

**Comment by SiverDX** [comment]
youre probably not gonan notice it breaking
there will be some random issues, maybe rendering related or sth. else about the behaviour of this mods entities compared to vanilla

good luck finding the cause

also good luck comparing the method after a couple versions when the code doesnt match up at all
better hope everyone is coding very cleanly and documenting everything (source, mc version etc) (lol not gonna happen, like ever)

then again im not a maintainer here so doesnt really matter

**Pull request closed without merging**
