### PR TITLE
Turn Gorgon Temple into a Jigsaw Structure

### LINKED ISSUE #3678: Gorgon Temples flooded with water
Every Gorgon Temple that spawns is flooded with water even though there’s no breach on the walls.

486125F7-A517-4CD7-A6F1-AB04E02F3A9C
B12DB7FF-AA11-42F0-922F-A9FC681A9E30

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Resolves: https://github.com/Alex-the-666/Ice_and_Fire/issues/3678

Basically that issue was caused by the terraforming that Minecraft does being applied to every nbt piece and causing any air space it makes below sealevel to be filled with water. Which then triggers a vanilla bug where it waterlogs the structure's own pieces as a result. Not good.

By turning the temple into a Jigsaw structure, now the terraforming only happens at the base of the exposed temple which keeps the basement dry.

Things to note:
The temple is split up into 3 nbt files. The building, the basement, and the gorgon. Each has their own pool. The building has a downward jigsaw block that connects to the basement's upward jigsaw block. I had to put 2 piston/redstone block under two of the always on switches due to redstone dust not properly updating its state when crossing between jigsaw pieces. The piston seems to keep its state just fine.

The basement has a second upward jigsaw block that points to the gorgon pool that will spawn the gorgon nbt file with the mob (that has persistence set to true). I did a pool for the mob so you can add more entries to the pool to randomize what mob spawns or what kind of gorgon. Could even randomize what status buff the gorgon has.

The gorgon piece class is deleted as it is now useless. Instead, I made a dummy piece class to keep under the old gordon piece class registry name. This is to prevent logspam for existing worlds. However, you can remove this dummy piece and put in a log filter to silence the logspam if it is your piece like this: https://github.com/TelepathicGrunt/RepurposedStructures/blob/6b730683e6ce950846e853fb2d25a41e7b77d2e2/src/main/java/com/telepathicgrunt/repurposedstructures/utils/LogSpamFiltering.java#L56

Otherwise, this should fix that waterlogging bug while also giving you now the opportunity to randomize the temple pieces. Heck, you can now add on processors easier and make it randomize the blocks in the temple so it isn't the same every single time.

Hope this helps! be sure to test this first. I couldn't run Ice and Fire in dev due to missing client classes (TabulaModelAccessor) from the github. So I copied the temple files to my other test mod and made sure it was working there. But again, double check my work in the actual ice and fire mod but it should work just fine.

### CODE REVIEW

**Comment by TheBv** [comment]
Do you think this would be possible to do for the mausoleum/graveyard as well? 
We've had some generation issues with those as in them freezing the world generation thread  #3390. I wrote a hot fix for it some time ago but I'm still not convinced that it fixes the issue completely so I think it'd be cool if that issue could be ruled out completely forever.

**Comment by TelepathicGrunt** [comment]
Yeah the other structures can be turned into jigsaw structures as well. Since the others are just basically a single piece, it should be super easy to convert. 

Though the freezing you linked is interesting. There is one other worldgen hanging I know of and that's when a structure replaces a light producing block already placed in the world, a vanilla bug is triggered and crashes the lighting threads and cause the world hang forever. The solution for that bug is this mixin which me and several mods are using (the mixin is compatible with it itself so it doesnt conflict if a ton of mods uses it. (https://github.com/TelepathicGrunt/WorldBlender/blob/master/src/main/java/com/telepathicgrunt/worldblender/mixin/dimensions/WorldLightManagerMixin.java)

Probably wouldn't hurt to include that to make sure it isn't a lighting thread bug issue. But then again, the freeze you linked may be something different.

Give me a moment and I'll try and make the other structures into jigsaws

**Comment by TelepathicGrunt** [comment]
There, try that. make sure it all looks good and everything is spawning correctly.

**Comment by TheBv** [comment]
The generation seems to work perfectly!
Gorgon temples can sometimes still be flooded though :/ [screenshot1](https://user-images.githubusercontent.com/12676257/111044615-dff84180-8449-11eb-912f-d5c10724eaf2.png) [screenshot2](https://user-images.githubusercontent.com/12676257/111044616-e1296e80-8449-11eb-9212-9403da5e3331.png)
Also the mausoleum spawners aren't spawning the right mobs they all turned into pig spawners :/
The graveyard works perfectly though!

**Comment by TelepathicGrunt** [comment]
The flooding should be a lot less now instead of always. To reduce flooding some more, you could try only overriding func_230363_a_ (shouldStartAt in yarn) and check the ocean floor heightmap around in that area. And if the ocean floor is below sealevel - 4, return false to prevent structure gen. (also, this is where the `if (i2 >= 60) {` check you have should be in in order to prevent /locate giving false positives)
https://github.com/TelepathicGrunt/RepurposedStructures/blob/6b730683e6ce950846e853fb2d25a41e7b77d2e2/src/main/java/com/telepathicgrunt/repurposedstructures/world/structures/FortressJungleStructure.java#L31-L40

As for the mausoleum, weird. It had pig spawners when I was using ice and fire's latest jar with a few mods. Didn't know it was a bug. I'll try and fix that

**Comment by TelepathicGrunt** [comment]
Hmm. The mausoleum's nbt file shipped with the latest jar shows the spawner's nbt is saved with pig spawners. Weird.
image

These can be edited to the correct mob to spawn by using nbtexplorer. That would explain why spawning the mausoleum nbt with a Structure Block to look at it made it had pig spawners lol. Mystery solved.

It will be a bit before I have time to get back to this (I should've done my classwork projects first lol) so you can give a shot at modifying this PR if you want to get something merged soon

**Comment by TheBv** [comment]
Alright thanks for the info!
I'll take a look at it tomorrow

**Comment by TheBv** [comment]
So the mobspawners aren't correct because they used to get modified by a StructureProcessor called DreadRuinProcessor.
This one added the loot for the chests, set the entities to be spawned by the spawners and randomly added cracked stones.
I'm looking into reincoperating it into the current code but this might take some time since I have never done that...
Edit: also the torches need to be updated to face the correct wall I've spotted some code that does that for regular torches so I might be able to just add dreadtorches.

**Comment by TelepathicGrunt** [comment]
Oh I missed the processor. My bad. The good news is hooking them up to jigsaws is super easy. You just need to make a codec for the processor, register it in FMLCommonSetupEvent's enqueueWork, and then call the processor's registry name in the pool file entries.

codec for the processor.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/6b730683e6ce950846e853fb2d25a41e7b77d2e2/src/main/java/com/telepathicgrunt/repurposedstructures/world/processors/AirProcessor.java#L19 

returns the registered instance of the processor.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/6b730683e6ce950846e853fb2d25a41e7b77d2e2/src/main/java/com/telepathicgrunt/repurposedstructures/world/processors/AirProcessor.java#L29

The processor itself being a supplier to its codec
https://github.com/TelepathicGrunt/RepurposedStructures/blob/6b730683e6ce950846e853fb2d25a41e7b77d2e2/src/main/java/com/telepathicgrunt/repurposedstructures/modinit/RSProcessors.java#L13

Where to call the processor 
https://github.com/Alex-the-666/Ice_and_Fire/pull/3692/files#diff-f05e3a7207f5808710e9e6bd0de2535cab52f118f9461f0361b5cbe325c9acd8R9

**Comment by TelepathicGrunt** [comment]
@TheBv I got some time over the next few days that I can help out again. If you did some work already, can you push it to this PR so I can see what you have done so far? Or is everything finished already?

**Comment by TheBv** [comment]
@TelepathicGrunt I created a PR for your branch a while ago. Since I'm not a maintainer of this project I can't push anything directly, although I guess it might seem like I am :p . Alex (the maintainer) is quite busy so most fixes recently have been done so by the community. I'm just a guy with too much free time enjoying fixing bugs for this mod. 
One thing I mentioned in the PR was that the pond generation can destroy parts of the mausoleum, which shouldn't happen.
I looked into it a bit but I decided to work on other things in the meantime since you have a lot more experience than me.

**Comment by TelepathicGrunt** [comment]
Ah yeah the lake destroying structures is a vanilla thing. Even vanilla mansions gets wrecked by lakes. But Mojang did add code into the lakes to prevent it from spawning in villages. I hijack that myself with a mixin to add my villages and mansions into it to prevent lakes from spawning in my structures. The mixin can be copied for this as well as it won't conflict with other mixins to the same spot.

<https://github.com/TelepathicGrunt/RepurposedStructures/blob/master/src/main/java/com/telepathicgrunt/repurposedstructures/mixin/NoLakesInStructuresMixin.java>

**Comment by TelepathicGrunt** [comment]
Alright I figured out how to clone from a fork's branch so I'll PR additional stuff to your branch instead. I'll close this pr and our combined work on your branch can be PRed instead when finished

**Pull request closed without merging**
