### PR TITLE
Fix/frost lightning lily being switched (1.19.2)

### LINKED ISSUE #5114: [Bug]: No Lightning Lilys in the savana or messa biomes
### What happened?

Strangly I'm finding ice lilys in the savana, but we all know it's lightning lily that should be there!

### Minecraft Version

1.19

### Ice and Fire version

1.19.2-2.1.3-beta-3

### Citadel version

2.1.4-1.19

### Relevant log output

_No response_

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

### PR DESCRIPTION
**Pull request by SiverDX**
fixes #5114

just cherry pick this for 1.20.1 tbh

### CODE REVIEW

**Comment by SiverDX** [comment]
@TheBv you need to add this to 1.20 as well

**Comment by SiverDX** [comment]
\+ run datagen

**Comment by TheBv** [comment]
I don't see it being swapped https://github.com/AlexModGuy/Ice_and_Fire/blob/09f3f942d16e48f98d535b7ad1e62d1c53e7beaa/src/main/java/com/github/alexthe666/iceandfire/datagen/IafPlacedFeatures.java#L74
Am I missing something?

**Comment by SiverDX** [comment]
never mind, was my bad then

**Pull request merged**
