### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by ETStareak**
For new version.

### CODE REVIEW

**Comment by liach** [comment]
赞赞赞

**Comment by AlexModGuy** [comment]
could you do the entity.pixie.name too?

**Comment by ETStarLight** [comment]
@Alex-the-666  I have not seen what you talk about!265lines,anything I haven't finish?

**Comment by ETStareak** [comment]
@Alex-the-666  I am going tointroduce your mod to Chinese players,so I need your repost to release a Chinese post.I will NOT take any credits of the mod and all the link will direct to your official website. I do need your permission to do this, so are you ok with that?
Another mod I had do about that:[https://github.com/micdoodle8/Galacticraft/pull/1594](url) I do what joccob did.

**Comment by AlexModGuy** [comment]
Sure that sounds great. I'm most likely going to release a big version with the new mobs this weekend if all goes well, so you might want to wait until then.

**Pull request merged**
