### PR TITLE
Update for 1.12.2 Forge 2545

### PR DESCRIPTION
**Pull request by ghost**
i tested many of the mod features like in worldgeneration or items, didnt face with any error or something else. hope it's ok :D 
btw you can release an alpha or beta on curseforge with this. it deserves.

### CODE REVIEW

**Comment by Xorbah** [comment]
Wait, you compiled it for 1.12.2?

**Comment by ghost** [comment]
yeah?

**Comment by Sunconure11** [comment]
@Alex-the-666 You should merge this. It fixed a minor oversight with my own set up of the JSON recipes, and fixed whatever happened to the mappings on the repo.

**Comment by AlexModGuy** [comment]
@Sunconure11 still not compatable

**Comment by ghost** [comment]
the compatibility is all about imports, why don't you organize them? it's very free by pressing ctrl+shift+O in eclipse

**Comment by Sunconure11** [comment]
He uses IntelliJ. It has a similar function when you optimize imports.

I'd advise recreating the mapping changes, @Alex-the-666, as these commits keep conflicting with the rest of it.

**Comment by NovaViper** [comment]
Did this pull get merged?

**Pull request closed without merging**
