### PR TITLE
Fixed myrmex issues

### PR DESCRIPTION
**Pull request by TheBv**
Fixed casting issues that were caused from my implementation of the pathfinding stuff for myremex' .

### CODE REVIEW

**Comment by Daejangnamu** [comment]
New server crash
https://gist.github.com/Daejangnamu/d6490eda7e97c44bd737b159ec8d2851

**Comment by TheBv** [comment]
This should be fixed now.
I might continue working on this later since currently the royal myrmex isn't using the climbing path navigator like it used to originally. But as far as I'm aware alex made the same compromise. If myrmex should climb things like spiders I might get back to it.

**Comment by Daejangnamu** [comment]
It works without problems. Thank you

**Comment by Daejangnamu** [comment]
Could you give me the Discord name? I have something to ask

**Comment by TheBv** [comment]
Sure it's Bv#0365

**Comment by TheBv** [comment]
This should hopefully now address almost all points mentioned here: #3290
1. No more crashes on egg hatching. 
2. Reputation works properly now
3. Myrmex worker should now pickup resin/any item that they should prioritize
4. Myrmex eggs shouldn't despawn on chunck loading anymore
(More details are in the commits)

I hope I fixed the TPS issues which as far as I'm aware were caused by Myrmex' that got stuck and kept expanding the wanderingRadius. I implemented a maximum Radius and I'm also increasing the wandering radius exponentially to combat this.
Also to reduce TPS issues on loading a hive I added an NBT tag for each hive that keeps track of the current wanderingRadius that every worker now shares.

I fixed myrmex' missing a lot of times by moving the damage dealt to the attackEntityAsMob function for the worker and the soldier, since those were causing the most issues. They don't 100% attack like they used to since I'm not dealing the damage at specific animation ticks but it's pretty similar. 

I'm 99% certain that  #3275 and similar issues are caused by the sentinel picking up a mob. I might fix that but that would be in a different draft.

If anyone wants something implemented differently let me know and I'll change things!

Oh I almost forgot: This also fixes the remaining egg throwing issues.

Note
This should also hopefully fix: #3295,#3320,#3334

**Comment by Daejangnamu** [comment]
https://gist.github.com/Daejangnamu/45c73b9849bdb2a1d49675528d62b665

Crash occurs when Myrmex and Crocodile(Alex-mobs) fight.

**Pull request merged**
