### PR TITLE
Move Features to DR

### PR DESCRIPTION
**Pull request by Matyrobbrt**
This PR moves Features to DeferredRegister, in order to fix a bug pointed out by @TheBv, after entity types have been moved to DR.

### CODE REVIEW

**Comment by TheBv** [comment]
The same thing needs to be done for the structures. But I can also create a pr for your fork if you want me too and you can focus on your other stuff :)

**Comment by Matyrobbrt** [comment]
Nah, I can quickly move the structures as well. The only ones that can't be moved are the configured features.

**Comment by Matyrobbrt** [comment]
@TheBv Structures have been moved as well, and there is no more spam logging.

**Comment by TheBv** [comment]
Looks good!
Thanks :)

**Pull request merged**
