### PR TITLE
How About This One (1.12.2 - Forge 2555 Update)

### PR DESCRIPTION
**Pull request by ghost**
I think it's clearer to merge. I didn't organize imports, just fixed types and some other small things. You can see them in commits...
Have also tested in the game, all works fine...

### CODE REVIEW

**Comment by ghost** [comment]
also, if you want, i can organize all imports again to improve performance. it really makes difference. because there are too many unused imports.
_i didn't organize them in this pull request to make it clearer._

**Comment by Sunconure11** [comment]
It's conflicting again. You should probably fix the conflict, and contact the dev.

**Comment by ghost** [comment]
ffs, it wasnt conflicting, so now because of the commit that been made about an hour ago by alex.
...
can you help me about how can i get that commit on my forked side without losing all my fork?
all i want is not deleting the repository then forking it again.

**Comment by ghost** [comment]
btw, i fixed it; i copied the new version of DragonAIWaterTarget.java class then updated again. it still says conflicting but it does not in real.. you can see it...

**Comment by ghost** [comment]
ok im giving up. ill not make pull request again, trust me :D

**Pull request closed without merging**
