### PR TITLE
(1.16) Move IafEntityRegistry to DeferredRegister

### PR DESCRIPTION
**Pull request by Matyrobbrt**
This PR moves `IafEntityRegistry` to using `DeferredRegister` instead of static init, future-proofing ports to 1.18+.
**Depends on #4451**

### CODE REVIEW

**Comment by AlexModGuy** [comment]
has conflicts

**Comment by Matyrobbrt** [comment]
Conflicts fixed @Alex-the-666

**Comment by TheBv** [comment]
Seems to break WorldGen features. Not sure if it's exactly this commit since other's messed with when what gets registered as well.
Also getting INFO logs which weren't there before which probably are related.
Part of the log file when generating/joining a world:
[log_part.log](https://github.com/Alex-the-666/Ice_and_Fire/files/8597239/log_part.log)

**Comment by TheBv** [comment]
Found the issue.
`RegistryEvent.Register<Feature<?>>` gets called before the world registry gets registered.
I think I'll switch to deferred registers for them that should fix it.

**Comment by Matyrobbrt** [comment]
So, I looked at it, and before worldgen related registries were setup at static init. Unfortunately, due to the fact that EntityTypes have been moved to DR, that can no longer be done. I've done some testing and it seems like there are 2 alternatives here:
- move the feature registry to DR
- move the registration of features to `RegistryEvent.Register<Feature<?>>`

**Comment by Matyrobbrt** [comment]
> Found the issue. `RegistryEvent.Register<Feature<?>>` gets called before the world registry gets registered. I think I'll switch to deferred registers for them that should fix it.

Do note, that isn't fully possible. `ConfiguredFeature` is not wrapped by Forge, and such can't be used for DR in 1.16. The `ConfiguredFeature`s will **have** to be registered in `RegistryEvent.Register<Feature<?>>`.

**Pull request merged**
