### PR TITLE
Small fixes

### LINKED ISSUE #3909: Gorgon Corrupted Chunk [2.1.6]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Upon being killed/stoned by a Gorgon, the chunk went corrupt, crashing the player killed and kicking all other players in the chunk. After being disconnected, all players caught in it were greeted to a message saying the NBT data was too large.

gist of my log:
https://gist.github.com/Skyibis/c99a1b29edca89881672201cacd3a15f
gist of another player who was caught in the crash's log:
https://gist.github.com/Skyibis/b0f63cbd250b8a0409911a100ccd9911

**To Reproduce**
Be killed by a Gorgon on latest version

**Expected behavior**
To be killed normally

**Screenshots**

**Additional context**
The crash was followed with errors following NBT data being too large. I am playing with enhanced visuals, and I had recently experienced a bug with them involving instant kills and the damage handler causing the client to hang and become unresponsive. We got it patched, but I suspect this might be a possible cause. I'm playing on a custom modpack and I recognize this might be an issue that is unrelated to your mod. I haven't done any more testing, but I thought you could provide some light by looking at the crash log and seeing if its something relating to your mod or something I should fix elsewhere. Thank you!

### LINKED ISSUE #4076: Gorgon Turning to Stone Crashes Server [2.1.8]
**Describe the bug**
Anytime a Gorgon turns a player to stone on a server, either via head or the gorgon herself, the player is forcibly disconnected with the error message shown in the screenshot. Anytime another player attempts to get close they are kicked as well.
We are using the modpack Lennbain, version 2.1.0. 

**Screenshots**
image

### LINKED ISSUE #4091: Error spam [iceandfire-2.1.8-1.16.5.jar]
**Describe the bug**
At some point when forcefully removing spawned mobs, the server console begins to spam with errors.

**To Reproduce**
Install BadMobs and disable Drowned from spawning.

**Additional context**
https://pastebin.com/raw/gqNeWcMe

### LINKED ISSUE #4112: Missing toLowerCase causes bestiary entries crash game under simplified chinese localization
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
Client crashes when clicking any entry in bestiary, when playing under zh_cn localization. Possibly caused by upper case language label zh_CN. Addition of function toLowerCase is required in iceandfire/client/gui/bestiary/GuiBestiary.java, line 788, from by interpretation.

**To Reproduce**
Set your game language to zh_CN '简体中文（中国）', then enter any game and open any entry of bestiary.

**Expected behavior**
Localized bestiary entries are expected to be accessed.

**Screenshots**
N/A

**Additional context**
crash-report:
https://gist.github.com/Apot98/53c0434a3e8c9a677def5dfb0c46e532

### LINKED ISSUE #4113: Scribe villager houses generating too often, not allowed to reduce rates/disable the structure in config [2.1.8]
Not sure if this technically counts as a bug, but I am posting it as such. The new village scribe buildings spawn way too often in villages, and the option to change the weight in the config does not allow reducing the value lower than the default (30) or disabling the structure.

bruhh

### LINKED ISSUE #4118: Cannot Get Pixie House DirectionProperty  [2.1.8-1.16.5]
**Describe the bug**
Extremely random crash, could be a chunk load delay thing: https://hastebin.com/nakipehoce.rb

**To Reproduce**
I have no idea. Seemingly random crash in a world that i had played in for hours.

**Expected behavior**
Pixie house doesnt cause a crash.

### LINKED ISSUE #4135: Rendering Block Entity Pixie Houses [ICE AND FIRE VERSION 2.1.8]
Alot of our players and myself included get random crashes when in a biome where pixies and their houses are. 
[crash-2021-08-06_23.07.09-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6946381/crash-2021-08-06_23.07.09-client.txt)

### LINKED ISSUE #4144: Swastika in one of the village houses added by ice and fire 2.1.8 1.16.5
A very clear swastika appears in the savanna variant of the bestiary house in the glass on the ceiling

1. Locate savanna biome
2. Find a bestiary house (crackled cobblestone, acacia wood, desert myrmex glass ceiling, bestiary lectern inside, etc.)
3. Look up at the glass ceiling
4. Profit

Man idk lmao theres just a swastika on the roof and i dont know if yall know its there

https://user-images.githubusercontent.com/73063302/128846215-e8bd8914-f10d-486f-a9fb-8f33f15bd502.png
idk how to do images in github sorry homies

### LINKED ISSUE #4146: Tide Trident won't work correctly.
Whenever I throw the trident and go to pick it up, it gives me a normal Minecraft trident instead of the one I threw. Does anyone know why this is happening to me?

### LINKED ISSUE #4150: Stacktrace error overload causes server to lag to death [2.1.8-1.16.5]
**Describe the bug**
On our small community Minecraft server using the Tide Trident kicks off a crash, every use of it throws up a stacktrace error which caused the server to fall so far behind in ticks it lagged itself to death, it also caused a strange (maybe unrelated?) issue of showing 22 people online, when we are a private server and don't have even a 1/4 of that in total players. A server reset seemed to fix that though

**To Reproduce**
1. Get a Storm Trident
2. Yeet a Storm Trident
3. Stacktraces out the wazzo
4. Server dies to death
5. Profit?

**Expected behavior**
The storm trident should work without lagging the server to death, I'm wondering if it's the mod alone or conflict with other mods that's the issue.

**Screenshots**
We didn't get any screenshots of this happening

**Additional context**
I've attached two logs around the time the error happened as well as the full mod list, if any other info is needed I can obtain it upon request.
[2021-08-13-1.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6985427/2021-08-13-1.log)
[2021-08-12-2.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6985430/2021-08-12-2.log)
[modlist.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6985431/modlist.txt)

### PR DESCRIPTION
**Pull request by TheBv**
This fixes the following:

- Render crash related to pixie houses (resolves #4135, resolves #4118)
- Fixed bestiary crash related to language paths (resolves #4112)
- Fixed some issues related to the Tide trident (resolves #4091, resolves #4150, resolves #4146)
- Should fix issues related to gorgons creating stone statues with too much NBT data (resolves #4076, resolves #3909)
- Increased the configurable range for villager houses IaF adds (resolves #4113)
- The glass from villager scribe houses creating unwanted patterns (resolves #4144)
This was achieved by removing the orientation properties of the various glass blocks since they'd be "scrambled" whenever a house gets rotated otherwise

This PR also upgrades the citadel version to 1.7.3 since I wanted to fix a lot of the issues relate to the FrozenEntityProperty but:
@Alex-the-666 I saw that you deprecated a lot of the older ways to register custom Properties ever since citadel version 1.7.2
If you have a rough outline on how you plan to update the current Iaf code to not use the deprecated classes please let me know and I'll implement those.
In addition I am of the opinion that the current/previous way to initialize the properties is flawed, since the way properties get initialized is tied into nbtdata reading/writing(`CitadelEvents#onAttachCapabilities`). Which is introducing two issues:
- Only properties related to server-level entities will be initialized meaning client-level properties won't ever have an entity value (which is needed e.g in `ClientEvents#onPreRenderLiving`)
- When an entity spawns "naturally" in the world `CitadelEvents#onAttachCapabilities` won't be called which means the corresponding properties for the entities won't be initialized, unless you reload the world, which seems to be the main cause for the crashes.

My suggestion would be to initialize the properties not only in `CitadelEvents#onAttachCapabilities` but also in `CitadelEvents#onEntityConstructing` which should fix most of the crashes as this hook get's called for both server and client entities. Additonally `EntityProperties#getEntity` should have a null check
I'd create a PR to fix this myself but I'm uncertain as to what you have planned for the EntityProperties since you deprecated most of it.

A list of issues that are all related to the EntityProperties issue: #4133, #4134, #4132, #4125, #4123,  #4122, #4120, #4119,  #4114, #4110, #4103, #4099, #4094, #4093, #4088, #4087,  #4085, #4080, #4078...

### CODE REVIEW

**Comment by iamryabinov** [comment]
Hello! How can I build and try your version?

**Comment by TheBv** [comment]
@iamryabinov I went ahead and build the repo you can find it on my branch under releases.
I've created two different builds:

- This [one](https://github.com/TheBv/Ice_and_Fire/releases/tag/0.2) exactly mirrors the changes described in the PR and therefor doesn't fix any issues related to EntityProperties.
- Hence I built a second version which does address these issues which can be found [here](https://github.com/TheBv/Ice_and_Fire/releases/tag/0.2.1). Just keep in mind that I quickly whipped together those changes in less than 10 minutes and I also haven't thoroughly tested them (They do seem to work nicely though)

A reminder for both of them: I am not the creator of this mod and these builds are in no way approved by Alex(the creator of the mod) himself. Use at your own risk!

If you still have any errors that are related to the above issues please let me know and I'll take a look at it!

**Comment by AlexModGuy** [comment]
> This PR also upgrades the citadel version to 1.7.3 since I wanted to fix a lot of the issues relate to the FrozenEntityProperty but:
@Alex-the-666 I saw that you deprecated a lot of the older ways to register custom Properties ever since citadel version 1.7.2
If you have a rough outline on how you plan to update the current Iaf code to not use the deprecated classes please let me know and I'll implement those.

Essentially, the plan is to move all of the EntityProperties systems into essentially raw NBT tags stored by citadel with mixins into LivingEntity. I depreciated these in 1.7-ish of citadel but I plan to fully transition to the new system when I update IAF(the only mod that still uses the EntityProperties system) to MC 1.17.1.

**Comment by AlexModGuy** [comment]
*CitadelEntityData

**Comment by TheBv** [comment]
Alright I'll mark this as ready for review and potentially create a PR fixing the EntityProperties issues similar to how I did [here ](https://github.com/TheBv/Ice_and_Fire/tree/entityPropsFix) later.

**Pull request merged**
